image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Deploy to Ubuntu Server
        deployment: production
        script:
          - pipe: atlassian/ssh-run:0.4.2
            variables:
              SSH_USER: 'iyesoft'
              SSH_KEY: '$SSH_KEY'
              SERVER: '$SERVER_IP_ADDRESS'
              MODE: 'script'
              COMMAND: |
                whoami
