image: php:8.1

pipelines:
  default:
    - step:
        name: Deploy to Ubuntu Server
        deployment: production
        script:
          - apt-get update && apt-get install -y openssh-client
          - echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          - chmod 400 ~/.ssh/id_rsa
          - ssh-keyscan -H $SERVER_IP_ADDRESS >> ~/.ssh/known_hosts
          - cat ~/.ssh/id_rsa
          - ssh iyesoft@103.115.199.57 "whoami"
