name: Automatic Deployment on Ubuntu Server

on:
  push:
    branches: [ "main" ]

jobs:
  laravel-deployment:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: laravel deployment
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: 103.115.199.57
          username: iyesoft
          key: ${{ secrets.IYESERVERSSH }}
          script: |
            cd /var/www/pakdss.com
            php artisan down
            git branch
            git reset --hard
            git checkout main
            git pull origin main
            php artisan optimize:clear
            php artisan optimize
            php artisan up
