name: Laravel

on:
  push:
    branches: [ "main" ]

jobs:
  jone_one:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 103.115.199.57
        username: iyesoft
        key: ${{ secrets.IYESERVERSSH }}
        scripts: |
          cd /var/www/pakdss.com
          git branch
          git pull origin main
          git status
